### ISSUE TITLE
如何设置AppId？

### ISSUE THREAD

**Issue by SmallElephant** [leancloud/leanengine-upgrade-3.0#1]
第一次使用LeanEngine引擎，当前目录没有任何应用信息，LC_APP_ID是需要在哪里设置呢?终端中输入avosCloud命令提示信心为“请使用：add <name> <app id> 关联应用。”

**Comment by wangxiao** [comment]
可以参考文档 https://leancloud.cn/docs/leanengine_guide-node.html ，里面也有 Demo，这类使用问题提到社区中吧。http://forum.leancloud.cn
